name: "Bicep Deploy Workflow"

on:
  push:
    branches:
      - main

env:
  subscription: 9f91d3ca-747b-4642-a795-c40a3d1f7bfd

jobs:
  bicepAzCliDeploy:
    name: Bicep Az CLI Deploy jobs
    runs-on: ubuntu-latest

    env:
      resource_group_name: rg-bicep-azcli-githubactions
      location: East US

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group
        uses: Azure/cli@v1.0.7
        with:
          inlinescript: |
            az deployment sub create \
            --name  ${{ env.resource_group_name }} \
            --location ${{ env.location }}
            --template-file ./bicep-templates/resourcegroup.bicep \
            --parameters \
            resourceGroupName=${{ env.resource_group_name }} \
            location="${{ env.location }}"

      - name: Deploy virtual network
        uses: Azure/cli@v1.0.7
        with:
          inlinescript: |
            az deployment group create \
            --resource-group ${{ env.resource_group_name }} \
            --template-file ./bicep-templates/virtualnetwork.bicep \
            --parameters \
              vNetPrefix=bicepazcli
              location="${{ env.location }}"
